import type { PostOnboardingConfig, ScreenId } from '../types/onboarding'
import { uid } from '../utils/config'
import { EditorSection, Field, TextField } from './EditorFields'

type Props = {
  value: PostOnboardingConfig
  screen: ScreenId
  onChange: (value: PostOnboardingConfig) => void
}

const clone = (value: PostOnboardingConfig) => JSON.parse(JSON.stringify(value)) as PostOnboardingConfig

export function PostOnboardingEditor({ value, screen, onChange }: Props) {
  const mutate = (recipe: (next: PostOnboardingConfig) => void) => {
    const next = clone(value)
    recipe(next)
    onChange(next)
  }

  const navigation = <EditorSection title="APP NAVIGATION" description="홈 이후 하단 탭에 공통으로 표시됩니다."><div className="editor-grid two"><TextField label="Home" value={value.navigation.home} onChange={(home) => mutate((next) => { next.navigation.home = home })} /><TextField label="Chat" value={value.navigation.chat} onChange={(chat) => mutate((next) => { next.navigation.chat = chat })} /><TextField label="Feed" value={value.navigation.feed} onChange={(feed) => mutate((next) => { next.navigation.feed = feed })} /><TextField label="Profile" value={value.navigation.profile} onChange={(profile) => mutate((next) => { next.navigation.profile = profile })} /></div></EditorSection>

  if (screen === 'serviceGuide') {
    const guide = value.guide
    return <>
      <EditorSection title="가입 완료 후 이용 안내" description="프로필 완료와 홈 사이에 한 번 표시되는 팝업 페이지입니다."><TextField label="Eyebrow" value={guide.eyebrow} onChange={(eyebrow) => mutate((next) => { next.guide.eyebrow = eyebrow })} /><TextField label="대제목" value={guide.headline} onChange={(headline) => mutate((next) => { next.guide.headline = headline })} multiline /><TextField label="설명" value={guide.description} onChange={(description) => mutate((next) => { next.guide.description = description })} multiline /><TextField label="하단 안내" value={guide.helper} onChange={(helper) => mutate((next) => { next.guide.helper = helper })} multiline /><TextField label="CTA" value={guide.cta} onChange={(cta) => mutate((next) => { next.guide.cta = cta })} /></EditorSection>
      <EditorSection title="이용 방식 설명" description="채팅·운영자 매칭·사용자 선택권을 원하는 순서로 편집합니다."><div className="editable-collection">{guide.points.map((point, index) => <div className="editable-card" key={point.id}><div className="editable-card-head"><b>{String(index + 1).padStart(2, '0')}</b><ReorderButtons index={index} length={guide.points.length} onMove={(direction) => mutate((next) => { move(next.guide.points, index, direction) })} onDelete={() => mutate((next) => { next.guide.points.splice(index, 1) })} /></div><div className="paired-fields"><TextField label="표시" value={point.icon} onChange={(icon) => mutate((next) => { next.guide.points[index].icon = icon })} /><TextField label="제목" value={point.title} onChange={(title) => mutate((next) => { next.guide.points[index].title = title })} /></div><TextField label="설명" value={point.description} onChange={(description) => mutate((next) => { next.guide.points[index].description = description })} multiline /></div>)}</div><button className="secondary-action" onClick={() => mutate((next) => { next.guide.points.push({ id: uid('guide'), icon: String(next.guide.points.length + 1).padStart(2, '0'), title: '새 안내', description: '설명을 입력해주세요.' }) })}>＋ 안내 항목 추가</button></EditorSection>
      <EditorSection title="운영자 직접 매칭 설명"><TextField label="Label" value={guide.operatorLabel} onChange={(operatorLabel) => mutate((next) => { next.guide.operatorLabel = operatorLabel })} /><TextField label="제목" value={guide.operatorTitle} onChange={(operatorTitle) => mutate((next) => { next.guide.operatorTitle = operatorTitle })} /><TextField label="설명" value={guide.operatorDescription} onChange={(operatorDescription) => mutate((next) => { next.guide.operatorDescription = operatorDescription })} multiline /></EditorSection>
    </>
  }

  if (screen === 'home') {
    const home = value.home
    return <>{navigation}<EditorSection title="HOME · 상단"><TextField label="Eyebrow" value={home.eyebrow} onChange={(eyebrow) => mutate((next) => { next.home.eyebrow = eyebrow })} /><TextField label="인사말 · {nickname} 사용 가능" value={home.greeting} onChange={(greeting) => mutate((next) => { next.home.greeting = greeting })} /><TextField label="설명" value={home.description} onChange={(description) => mutate((next) => { next.home.description = description })} multiline /></EditorSection><EditorSection title="프로필 상태 카드"><TextField label="Label" value={home.statusLabel} onChange={(statusLabel) => mutate((next) => { next.home.statusLabel = statusLabel })} /><TextField label="제목" value={home.statusTitle} onChange={(statusTitle) => mutate((next) => { next.home.statusTitle = statusTitle })} /><TextField label="설명" value={home.statusDescription} onChange={(statusDescription) => mutate((next) => { next.home.statusDescription = statusDescription })} multiline /></EditorSection><EditorSection title="운영자 매칭 카드"><TextField label="Label" value={home.operatorLabel} onChange={(operatorLabel) => mutate((next) => { next.home.operatorLabel = operatorLabel })} /><TextField label="제목" value={home.operatorTitle} onChange={(operatorTitle) => mutate((next) => { next.home.operatorTitle = operatorTitle })} /><TextField label="설명" value={home.operatorDescription} onChange={(operatorDescription) => mutate((next) => { next.home.operatorDescription = operatorDescription })} multiline /><TextField label="CTA" value={home.operatorCta} onChange={(operatorCta) => mutate((next) => { next.home.operatorCta = operatorCta })} /></EditorSection><EditorSection title="작은 소식"><TextField label="섹션 제목" value={home.updatesTitle} onChange={(updatesTitle) => mutate((next) => { next.home.updatesTitle = updatesTitle })} /><TextField label="항목 · 줄바꿈으로 구분" value={home.updates.join('\n')} onChange={(text) => mutate((next) => { next.home.updates = text.split('\n') })} multiline /></EditorSection></>
  }

  if (screen === 'chat') {
    const chat = value.chat
    return <>{navigation}<EditorSection title="CHAT · 상단"><TextField label="Eyebrow" value={chat.eyebrow} onChange={(eyebrow) => mutate((next) => { next.chat.eyebrow = eyebrow })} /><TextField label="대제목" value={chat.headline} onChange={(headline) => mutate((next) => { next.chat.headline = headline })} /><TextField label="설명" value={chat.description} onChange={(description) => mutate((next) => { next.chat.description = description })} multiline /><TextField label="빈 화면 문구" value={chat.emptyText} onChange={(emptyText) => mutate((next) => { next.chat.emptyText = emptyText })} multiline /></EditorSection><EditorSection title="운영자 안내 대화"><TextField label="제목" value={chat.operatorTitle} onChange={(operatorTitle) => mutate((next) => { next.chat.operatorTitle = operatorTitle })} /><TextField label="설명" value={chat.operatorDescription} onChange={(operatorDescription) => mutate((next) => { next.chat.operatorDescription = operatorDescription })} multiline /><TextField label="CTA" value={chat.operatorCta} onChange={(operatorCta) => mutate((next) => { next.chat.operatorCta = operatorCta })} /></EditorSection><EditorSection title="샘플 채팅 목록"><div className="editable-collection">{chat.rooms.map((room, index) => <div className="editable-card" key={room.id}><div className="editable-card-head"><b>ROOM {index + 1}</b><ReorderButtons index={index} length={chat.rooms.length} onMove={(direction) => mutate((next) => { move(next.chat.rooms, index, direction) })} onDelete={() => mutate((next) => { next.chat.rooms.splice(index, 1) })} /></div><div className="paired-fields"><TextField label="이름" value={room.name} onChange={(name) => mutate((next) => { next.chat.rooms[index].name = name })} /><TextField label="상태" value={room.status} onChange={(status) => mutate((next) => { next.chat.rooms[index].status = status })} /></div><TextField label="미리보기" value={room.preview} onChange={(preview) => mutate((next) => { next.chat.rooms[index].preview = preview })} multiline /><TextField label="시간" value={room.time} onChange={(time) => mutate((next) => { next.chat.rooms[index].time = time })} /></div>)}</div><button className="secondary-action" onClick={() => mutate((next) => { next.chat.rooms.push({ id: uid('room'), name: '새 대화', preview: '미리보기 메시지', time: '방금', status: '대화중' }) })}>＋ 채팅 예시 추가</button></EditorSection></>
  }

  if (screen === 'chatRoom') {
    const room = value.chatRoom
    return <>{navigation}<EditorSection title="CHAT ROOM · 공통"><TextField label="방 제목" value={room.title} onChange={(title) => mutate((next) => { next.chatRoom.title = title })} /><TextField label="상태 설명" value={room.subtitle} onChange={(subtitle) => mutate((next) => { next.chatRoom.subtitle = subtitle })} /><TextField label="안전 안내" value={room.systemNotice} onChange={(systemNotice) => mutate((next) => { next.chatRoom.systemNotice = systemNotice })} multiline /><TextField label="입력 Placeholder" value={room.inputPlaceholder} onChange={(inputPlaceholder) => mutate((next) => { next.chatRoom.inputPlaceholder = inputPlaceholder })} /><TextField label="전송 Button" value={room.sendButton} onChange={(sendButton) => mutate((next) => { next.chatRoom.sendButton = sendButton })} /></EditorSection><EditorSection title="샘플 대화"><div className="editable-collection">{room.messages.map((message, index) => <div className="editable-card" key={message.id}><div className="editable-card-head"><b>MESSAGE {index + 1}</b><ReorderButtons index={index} length={room.messages.length} onMove={(direction) => mutate((next) => { move(next.chatRoom.messages, index, direction) })} onDelete={() => mutate((next) => { next.chatRoom.messages.splice(index, 1) })} /></div><Field label="말풍선 위치"><select value={message.side} onChange={(event) => mutate((next) => { next.chatRoom.messages[index].side = event.target.value as typeof message.side })}><option value="system">System</option><option value="theirs">상대</option><option value="mine">나</option></select></Field><TextField label="메시지" value={message.text} onChange={(text) => mutate((next) => { next.chatRoom.messages[index].text = text })} multiline /><TextField label="시간" value={message.time} onChange={(time) => mutate((next) => { next.chatRoom.messages[index].time = time })} /></div>)}</div><button className="secondary-action" onClick={() => mutate((next) => { next.chatRoom.messages.push({ id: uid('message'), side: 'theirs', text: '새 메시지를 입력해주세요.', time: '방금' }) })}>＋ 메시지 추가</button></EditorSection></>
  }

  if (screen === 'feed') {
    const feed = value.feed
    return <>{navigation}<EditorSection title="FEED · 상단"><TextField label="Eyebrow" value={feed.eyebrow} onChange={(eyebrow) => mutate((next) => { next.feed.eyebrow = eyebrow })} /><TextField label="대제목" value={feed.headline} onChange={(headline) => mutate((next) => { next.feed.headline = headline })} /><TextField label="설명" value={feed.description} onChange={(description) => mutate((next) => { next.feed.description = description })} multiline /></EditorSection><EditorSection title="피드 글"><div className="editable-collection">{feed.posts.map((post, index) => <div className="editable-card" key={post.id}><div className="editable-card-head"><b>POST {index + 1}</b><ReorderButtons index={index} length={feed.posts.length} onMove={(direction) => mutate((next) => { move(next.feed.posts, index, direction) })} onDelete={() => mutate((next) => { next.feed.posts.splice(index, 1) })} /></div><div className="paired-fields"><TextField label="카테고리" value={post.category} onChange={(category) => mutate((next) => { next.feed.posts[index].category = category })} /><TextField label="메타" value={post.meta} onChange={(meta) => mutate((next) => { next.feed.posts[index].meta = meta })} /></div><TextField label="제목" value={post.title} onChange={(title) => mutate((next) => { next.feed.posts[index].title = title })} multiline /><TextField label="본문" value={post.body} onChange={(body) => mutate((next) => { next.feed.posts[index].body = body })} multiline /></div>)}</div><button className="secondary-action" onClick={() => mutate((next) => { next.feed.posts.push({ id: uid('feed'), category: '새 글', title: '제목을 입력해주세요.', body: '본문을 입력해주세요.', meta: '운영자 노트' }) })}>＋ 피드 글 추가</button></EditorSection></>
  }

  const profile = value.profile
  return <>{navigation}<EditorSection title="MY PROFILE · 상단"><TextField label="Eyebrow" value={profile.eyebrow} onChange={(eyebrow) => mutate((next) => { next.profile.eyebrow = eyebrow })} /><TextField label="대제목 · {nickname} 사용 가능" value={profile.headline} onChange={(headline) => mutate((next) => { next.profile.headline = headline })} /><TextField label="프로필 상태" value={profile.status} onChange={(status) => mutate((next) => { next.profile.status = status })} /></EditorSection><EditorSection title="현재 설정 요약"><TextField label="섹션 제목" value={profile.summaryTitle} onChange={(summaryTitle) => mutate((next) => { next.profile.summaryTitle = summaryTitle })} /><TextField label="만남 방식 Label" value={profile.matchingModeLabel} onChange={(matchingModeLabel) => mutate((next) => { next.profile.matchingModeLabel = matchingModeLabel })} /><TextField label="운영자 매칭 Label" value={profile.operatorMatchLabel} onChange={(operatorMatchLabel) => mutate((next) => { next.profile.operatorMatchLabel = operatorMatchLabel })} /><TextField label="운영자 매칭 값" value={profile.operatorMatchValue} onChange={(operatorMatchValue) => mutate((next) => { next.profile.operatorMatchValue = operatorMatchValue })} /></EditorSection><EditorSection title="관리 메뉴"><TextField label="섹션 제목" value={profile.menuTitle} onChange={(menuTitle) => mutate((next) => { next.profile.menuTitle = menuTitle })} /><TextField label="메뉴 · 줄바꿈으로 구분" value={profile.menuItems.join('\n')} onChange={(text) => mutate((next) => { next.profile.menuItems = text.split('\n') })} multiline /></EditorSection></>
}

function move<T>(items: T[], index: number, direction: -1 | 1) {
  const target = index + direction
  if (target < 0 || target >= items.length) return
  const [item] = items.splice(index, 1)
  items.splice(target, 0, item)
}

function ReorderButtons({ index, length, onMove, onDelete }: { index: number; length: number; onMove: (direction: -1 | 1) => void; onDelete: () => void }) {
  return <div className="editable-card-actions"><button disabled={index === 0} onClick={() => onMove(-1)} aria-label="위로">↑</button><button disabled={index === length - 1} onClick={() => onMove(1)} aria-label="아래로">↓</button><button className="text-danger" onClick={onDelete} aria-label="삭제">×</button></div>
}
